### ISSUE TITLE
Syntax Error after installing

### ISSUE THREAD

**Issue by lizard-heart** [lucasrla/remarks#42]
I cloned the repository like this: `git clone https://github.com/lucasrla/remarks.git && cd remarks`
Then I installed the requirements: `pip install -r requirements.txt`

But then, when I tried running remarks, with this:
`python -m remarks --help`

I get this:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "remarks/__init__.py", line 1, in <module>
    from . import conversion
  File "remarks/conversion/__init__.py", line 1, in <module>
    from .parsing import (
  File "remarks/conversion/parsing.py", line 106
    name_code = f"{tool}_{pen}"
```

I'm not sure if the problem is me installing it wrong, but it would be great if somebody could help.

**Comment by folofjc** [comment]
Did you use `pyenv` for your python environment? If you look at the readme [here](https://github.com/lucasrla/remarks#compatibility-and-dependencies), @lucasrla tested with python version `3.8.x`, which is also in the `pyproject.toml` file. Looks like you have python `2.7`. Python2 and Python3 are pretty different. I would install `pyenv` and then make sure that you have at least 3.8 installed. I am using 3.8.6 with this repo.
