### ISSUE TITLE
Error when attempting running script with --pdf_name

### ISSUE THREAD

**Issue by saccentekennedy** [lucasrla/remarks#45]
Hi there...

I'm not sure what I'm doing wrong here?

C:\Users\brian\Google Drive\Zotfile\remarks>python -m remarks "C:\Users\brian\Google Drive\Zotfile\remarks\desktop" "C:\Users\brian\Google Drive\Zotfile\remarks" --pdf_name "Sperry_Klich_1992_Speech Breathing in Senescent and Younger Women During Oral Reading" --targets pdf --combined_pdf
Traceback (most recent call last):
  File "C:\Users\brian\Python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\brian\Python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\brian\Google Drive\Zotfile\remarks\remarks\__main__.py", line 94, in <module>
    main()
  File "C:\Users\brian\Google Drive\Zotfile\remarks\remarks\__main__.py", line 90, in main
    run_remarks(input_dir, output_dir, **args_dict)
  File "C:\Users\brian\Google Drive\Zotfile\remarks\remarks\remarks.py", line 48, in run_remarks
    if not is_document(path):
  File "C:\Users\brian\Google Drive\Zotfile\remarks\remarks\utils.py", line 16, in is_document
    metadata = read_meta_file(path)
  File "C:\Users\brian\Google Drive\Zotfile\remarks\remarks\utils.py", line 11, in read_meta_file
    data = json.loads(open(file).read())
  File "C:\Users\brian\Python\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\brian\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\brian\Python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Any idea what I'm doing wrong?

**Comment by saccentekennedy** [comment]
And... any idea what is wrong with decoding this file? There is highlighted text all over the document, however I get the following error message:

C:\ZoteroRemarkable\remarks>python -m remarks C:/ZoteroRemarkable/Zotero C:/ZoteroRemarkable --targets pdf --combined_pdf
mupdf: cannot recognize version marker
Working on PDF file: c8fbe34e-cb9e-4a7e-a21d-b664109f642a
PDF visibleName: "Heller Murray et al_2017_The Impact of Glottal Configuration on Speech Breathing"
PDF in-device directory: .
mupdf: cannot recognize version marker
- Couldn't find any highlighted text on page #1
mupdf: cannot recognize version marker
mupdf: cannot recognize version marker
mupdf: cannot recognize version marker
mupdf: cannot recognize version marker
