### ISSUE TITLE
Compatibiltity with older highlight colors

### ISSUE THREAD

**Issue by opal06** [lucasrla/remarks#56]
I encountered the following error: 
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/$user/.programs/remarks/remarks/__main__.py", line 141, in <module>
    main()
  File "/home/$user/.programs/remarks/remarks/__main__.py", line 137, in main
    run_remarks(input_dir, output_dir, **args_dict)
  File "/home/$user/.programs/remarks/remarks/remarks.py", line 84, in run_remarks
    process_document(metadata_path, out_path, doc_type, **kwargs)
  File "/home/$user/.programs/remarks/remarks/remarks.py", line 332, in process_document
    ann_page = add_smart_highlight_annotations(smart_hl_data, ann_page)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/$user/.programs/remarks/remarks/conversion/drawing.py", line 186, in add_smart_highlight_annotations
    color_array = fitz.utils.getColor(HL_COLOR_CODES[hl["color"]])
                                      ~~~~~~~~~~~~~~^^^^^^^^^^^^^

KeyError: 0
```

From working on [zotero2remarkable_bridge](https://github.com/opal06/zotero2remarkable_bridge) I remember that at some point reMarkable shuffled around the number codes for their highlight colors and moved "Yellow" from 0 to 3. But they have not updated older highlights files that were created before, so you can still encounter code 0 for yellow. 

I think this could either be solved by adding 0 as an additional key mapped to yellow or add something like this to the add_smart_highlight_annotations function:
```python3
try:
     color_array = fitz.utils.getColor(HL_COLOR_CODES[hl["color"]])
except KeyError:
     color_array = fitz.utils.getColor(HL_COLOR_CODES[3]) # default to yellow if color is not yet defined
```

**Comment by lucasrla** [comment]
Hey @opal06, I _think_ I remember the change you're referring to. 

In any case, I've just pushed a commit with your sensible suggestion: [55eb1ad](https://github.com/lucasrla/remarks/commit/55eb1ad6198d336c77b7db53f0943a5f8c29663e).

Thanks!
